### ISSUE TITLE
my $_ is not allowed anymore in perl 5.23.4 and greater

### ISSUE THREAD

**Issue by eserte** [osv/csswatcher#1]
Please see https://rt.cpan.org/Ticket/Display.html?id=108297

**Comment by osv** [comment]
Thanks for report here, I don't know why I don't get email from rt.cpan.org about 3 bugs last day ago...

**Comment by eserte** [comment]
Maybe the email settings in https://pause.perl.org ("> Edit Account Info" link) are not correct? Maybe "neither nor" is seleced here?

**Comment by osv** [comment]
Indeed, "neither nor". Hm, I press submit, but it not apply my changes...

As for csswatcher,  I fix those 3 bugs in CSS-Watcher-0.4.5 version, however test matrix still not ready.

**Comment by osv** [comment]
test matrix looks clear now :)
